#!/bin/bash

echo "[1] Install packages for fish shell and nano editor."
if [[ -d ${XDG_CONFIG_HOME:-~/.config}/package-list ]];
then cd ${XDG_CONFIG_HOME:-~/.config}/package-list;
else cd $(dirname $(realpath -s $0))/../.config/package-list;
fi
su --shell=/bin/bash --command=\
"cat fish nano | pacman -Syu --needed --asexplicit -" || exit 1
cd -

echo "[2] Change login shell to fish and clean-up bash dotfiles."
chsh --shell /usr/bin/fish || exit 2
rm --verbose ~/.bash*
